eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
spring:
  application:
    name: gateway
server:
  port: 9101
zuul:
  host:
    connect-timeout-millis: 2000
    max-per-route-connections: 6000
    socket-timeout-millis: 6000
  routes:
    mng:
      path: /autoGarage/**
      serviceId: autoGarage
      stripPrefix: true
    client:
      path: /client/**
      serviceId: client
      stripPrefix: true

